server:
  port: 8080
  servlet:
    context-path: /api/v2
spring:
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test2
  jpa:
    show-sql: true

